version: '3.7'

services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  static:
  postgres_data: